---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pech-ai-bou
  labels:
    app: pech-ai-bou
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pech-ai-bou
  template:
    metadata:
      labels:
        app: pech-ai-bou
    spec:
      containers:
      - name: pech-ai-bou
        image: rverchere/pech-ai-bou:0.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        env:
        - name: HUGGINGFACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugginface-hub
              key: HUGGINGFACE_HUB_TOKEN
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: hugginface-hub
        resources:
          limits:
            #nvidia.com/gpu: 1
            nvidia.com/mig-3g.40gb: 1
      volumes:
      - name: hugginface-hub
        persistentVolumeClaim:
          claimName: hugginface-hub
      nodeSelector:
        node.k8s.ovh/type: gpu
