---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rat-ai-touille
  labels:
    app: rat-ai-touille
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rat-ai-touille
  template:
    metadata:
      labels:
        app: rat-ai-touille
    spec:
      containers:
      - name: rat-ai-touille
        image: rverchere/rat-ai-touille:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        env:
        - name: HUGGINGFACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugginface-hub
              key: HUGGINGFACE_HUB_TOKEN
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: hugginface-hub
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: hugginface-hub
        persistentVolumeClaim:
          claimName: hugginface-hub
      nodeSelector:
        node.k8s.ovh/type: gpu
