---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-ai-guette
  labels:
    app: b-ai-guette
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: b-ai-guette
  template:
    metadata:
      labels:
        app: b-ai-guette
    spec:
      containers:
      - name: b-ai-guette
        image: rverchere/b-ai-guette:0.0.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            # nvidia.com/gpu: 1
            nvidia.com/mig-3g.40gb: 1
        ports:
        - containerPort: 8501
        env:
        - name: HUGGINGFACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugginface-hub
              key: HUGGINGFACE_HUB_TOKEN
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: hugginface-hub
      volumes:
      - name: hugginface-hub
        persistentVolumeClaim:
          claimName: hugginface-hub
      nodeSelector:
        node.k8s.ovh/type: gpu