---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chocol-ai-tine
  labels:
    app: chocol-ai-tine
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chocol-ai-tine
  template:
    metadata:
      labels:
        app: chocol-ai-tine
    spec:
      containers:
      - name: chocol-ai-tine
        image: rverchere/chocol-ai-tine:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: HUGGINGFACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugginface-hub
              key: HUGGINGFACE_HUB_TOKEN
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: hugginface-hub
      volumes:
      - name: hugginface-hub
        persistentVolumeClaim:
          claimName: hugginface-hub
      nodeSelector:
        node.k8s.ovh/type: gpu
---
apiVersion: v1
kind: Service
metadata:  
  name: chocol-ai-tine
spec:
  selector:
    app: chocol-ai-tine
  ports:  
    - name: http
      port: 80
      targetPort: 8501
      protocol: TCP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hugginface-hub
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: chocol-ai-tine
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - chocol-ai-tine.devfest-toulouse.opsrel.io
      secretName: chocol-ai-tine-crt
  rules:
    - host: chocol-ai-tine.devfest-toulouse.opsrel.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: chocol-ai-tine
                port:
                  number: 80
