---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chocol-ai-tine
  labels:
    app: chocol-ai-tine
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chocol-ai-tine
  template:
    metadata:
      labels:
        app: chocol-ai-tine
    spec:
      containers:
      - name: chocol-ai-tine
        image: rverchere/chocol-ai-tine:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            # nvidia.com/gpu: 1
            nvidia.com/mig-3g.40gb: 1
        ports:
        - containerPort: 8501
        env:
        - name: HUGGINGFACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugginface-hub
              key: HUGGINGFACE_HUB_TOKEN
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: hugginface-hub
      volumes:
      - name: hugginface-hub
        persistentVolumeClaim:
          claimName: hugginface-hub
      nodeSelector:
        node.k8s.ovh/type: gpu