devicePlugin:
  config:
    create: true
    data:
      default: |-
        version: v1
        sharing:
          timeSlicing:
            resources:
              - name: nvidia.com/gpu
                replicas: 4
            renameByDefault: false
            failRequestsGreaterThanOne: false
    name: timeslicing-config

dcgmExporter:
  serviceMonitor:
    enabled: true