mig:
  strategy: none

devicePlugin:
  config:
    create: true
    data:
      default: ""
      mps:
        version: v1
        sharing:
          mps:
            resources:
            - name: nvidia.com/gpu
              replicas: 4
      timeSlicing:
        version: v1
        sharing:
          timeSlicing:
            resources:
              - name: nvidia.com/gpu
                replicas: 4
            renameByDefault: false
            failRequestsGreaterThanOne: false
    name: sharing-config

dcgmExporter:
  serviceMonitor:
    enabled: true