apiVersion: v1
kind: Pod
metadata:
  namespace: devfest
  name: mps-env-test
spec:
  runtimeClassName: nvidia
  restartPolicy: OnFailure
  containers:
  - name: mps-env-test
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    command: ["sleep", "9999"]
    resources:
      limits:
        nvidia.com/gpu: 1
