apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-operator
  name: vectoradd-cuda
spec:
  restartPolicy: OnFailure
  containers:
  - name: vectoradd-cuda
    # Source : https://catalog.ngc.nvidia.com/orgs/nvidia/teams/k8s/containers/cuda-sample
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0"
    resources:
      limits:
        nvidia.com/gpu: 1